name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install powdr
      run: git clone https://github.com/powdr-labs/powdr.git && cd powdr/powdr_cli && cargo install --path . && cd ../../
    - name: Run VM
      run: ./run.sh